#
#pre-defination path
#
SET (BOOST_ROOT D:/MyWorkspace/SDKx64/boost_1_58_0)
SET (EIGEN3_INCLUDE_DIR D:/MyWorkspace/SDKx64/eigen-3.2.6)
SET (FREEGLUT_INCLUDE_DIR D:/MyWorkspace/SDKx64/glsdk_0_5_2/freeglut/include)
SET (IGL_INCLUDE_DIR D:/MyWorkspace/SDKx64/libigl/include)
SET (NANOGUI_INCLUDE_DIR D:/MyWorkspace/SDKx64/libigl/external/nanogui/include)
SET (GLEW_INCLUDE_DIR D:/MyWorkspace/SDKx64/glew-1.13.0/include)
SET (GLFW_INCLUDE_DIR D:/MyWorkspace/SDKx64/glfw-3.1.1/include)
SET (NANOVG_INCLUDE_DIR D:/MyWorkspace/SDKx64/libigl/external/nanogui/ext/nanovg/src)
SET (NANOGUI_LIBRARY_DIR D:/MyWorkspace/SDKx64/libigl/external/nanogui/lib_x64)
SET (GLFW_LIBRARY_DIR D:/MyWorkspace/SDKx64/glfw-3.1.1/lib_x64)
SET (OPENGL32_LIBRARY_DIR "C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Lib/x64")
SET (FREETYPE_GL_INCLUDE_DIR D:/MyWorkspace/SDKx64/freetype-gl)
SET (FREETYPE_GL_LIBRARY_DIR D:/MyWorkspace/SDKx64/freetype-gl/build/Release)
SET (SOIL_INCLUDE_DIR D:/MyWorkspace/SDKx64/SOIL)
SET (SOIL_LIBRARY_DIR D:/MyWorkspace/SDKx64/SOIL)
SET (GLEW_LIBRARY_DIR D:/MyWorkspace/SDKx64/glew-1.13.0/lib_x64)
SET (FREEGLUT_LIBRARY_DIR D:/MyWorkspace/SDKx64/glsdk_0_5_2/freeglut/lib/Release)
SET (GLM_INCLUDE_DIR D:/MyWorkspace/SDKx64/glsdk_0_5_2/glm)
