### README

 1. Prerequisites
 2. Building
 3. Installing
 4. Contributing
 
#### 1. PREREQUISITES

 This project requires:

  * Cross-platform Make ([CMake](https://cmake.org/)) v2.6.2+
  * GNU Make or Microsoft Visual Studio 12+.
  * C++ Compilers (GNU and Visual Studio), support C++11.
  * [Boost C++ Libraries](http://www.boost.org) v1.50+ [HEADERS and LIBRARIES]
  * [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) v3.2.5+
  * [Unofficial OpenGL Software Development Kit](http://glsdk.sourceforge.net/docs/html/index.html) (glsdk) v0.5.2+
  * [libigl](https://github.com/libigl/libigl) v1.0
  * [The OpenGL Extension Wrangler Library](http://glew.sourceforge.net/) (GLEW) v1.10.0+
  * [GLFW](https://github.com/glfw/glfw) v3.1.1+
  * [Simple OpenGL Image Library](http://www.lonesock.net/soil.html) (SOIL) v
  * [Freetype GL](https://github.com/rougier/freetype-gl) v0.0.1+

#### 2. BUILDING
 
 This project uses the Cross-platform Make (CMake) build system. However, we
 have conveniently provided a wrapper configure script and Makefile so that
 the typical build invocation of "./configure" followed by "make" will work.
 For a list of all possible build targets, use the command "make help".

 NOTE: Users of CMake may believe that the top-level Makefile has been
 generated by CMake; it hasn't, so please do not delete that file.

#### 3. INSTALLING

 Once the project has been built (see "BUILDING"), execute "sudo make install".

#### 4. CONTRIBUTING

 * Chen.Yang (Initial CMake project)
